services:
  home-api:
    build: .
    container_name: home-api
    restart: always
    ports:
      - "8010:5000"  # Puerto Externo 8010 -> Interno 5000
    env_file:
      - .env         # <--- ESTA LÍNEA ES LA CLAVE
    environment:
      # Aseguramos que Flask escuche en todas las interfaces dentro del contenedor
      - FLASK_HOST=0.0.0.0
      # Si tenías variables hardcodeadas aquí (ej: ODOO_URL=http://odoo:8069), BÓRRALAS.